### PR TITLE
Update .travis.yml and add badges to README

### PR DESCRIPTION
**Pull request by juliohm**
This PR updates the Travis build, and add badges to the README.

Do you have Travis CI and CodeCov activated already for the project? It is a good idea to add a cron job in the repo settings in Travis CI to build every month regardless of changes to the code: https://docs.travis-ci.com/user/cron-jobs/

### CODE REVIEW

**Comment by yurivish** [comment]
Thanks! I haven't activated Travis CI or CodeCov for any of my repositories since they've mostly been for personal use – do you have any pointers on how I can do so?

**Comment by juliohm** [comment]
Of course! I think you just need to sign up in Travis CI with your GitHub account, and then lookup the repo after it is synced there. There will be a button next to the repo saying activate. Then you can look the link I shared in the previous comment, and setup the cron job. Another set of clicks :) 

After travis is configured, you can also sign up for CodeCov with github account, and it will automatically use the Travis CI as far as I remember.

More info: https://docs.travis-ci.com/user/tutorial/

**Comment by yurivish** [comment]
Done! :)

**Comment by juliohm** [comment]
Awesome! :)

Em seg, 11 de mar de 2019 às 23:37, Yuri <notifications@github.com>
escreveu:

**Comment by juliohm** [comment]
It is saying that the repository isn't active in Travis yet: https://travis-ci.org/yurivish/TuringPatterns.jl

Did you swipe the button next to the repo to activate it there?

**Pull request merged**
