### PR TITLE
Update package to new package system

### PR DESCRIPTION
**Pull request by juliohm**
Hi @yurivish , I appreciate if you can review this PR. It replaces the old `REQUIRE` files by `Project.toml` files in Julia v1.x. Thanks again for the package.

After you review and merge, please consider adding JuliaRegistrator and TagBot to the repository. That way you can comment on the latest commit with `@JuliaRegistrator register()` and the new version specified in the `Project.toml` will be released.

### CODE REVIEW

**Comment by yurivish** [comment]
Hi Júlio,

It seems you're making much better use of this package than I am these days. :-)

I added you as a collaborator to this repository. From a quick look at the changes in this PR, it looks good to me, and I'm happy to have you contribute without needing to run things by me first. So long as it's possible to easily use this package to generate cool images for non-geostats purposes, any changes along the lines of the ones you've made so far seem great to me.

Feel free to merge this if you think it's in a good state and thanks again for the contribution!

**Comment by juliohm** [comment]
Thank you @yurivish for adding me to the repo :) I will be careful to make sure the package does not loose its standalone functionality :+1:

**Comment by juliohm** [comment]
We still need to add JuliaRegistrator and TagBot to the repo. I couldn't find it listed on my settings. Probably just the owner of the repo can do this. Could you please take a look?

**Comment by yurivish** [comment]
Sure. I just added JuliaRegistrator and TagBot, and the [docs](https://github.com/JuliaRegistries/Registrator.jl?installation_id=948774&setup_action=install#details-for-triggering-juliaregistrator-for-step-2-above) sound like as  a collaborator you should be able to trigger them now that they've been added.

**Pull request merged**
