### PR TITLE
Implement GeoStats.jl API

### PR DESCRIPTION
**Pull request by juliohm**
Dear @yurivish ,

Feel free to merge or reject this PR. It contains the minimum modifications needed to adhere to the GeoStats.jl API. I've added an example of usage to the README, and a test suite with visual regression tests. The modification requires a new dependency, namely `GeoStatsBase.jl`. This dependency is very light and will always be light by design.

In case the modification is not aligned with your goals for the package, please let me know and I will create a new package with a file containing the contents of `src/geostats.jl` in this PR.

Also, I appreciate if you can tag a release in the METADATA. I am planning to give a workshop in August, and will ask participants to install your solver :+1:

### CODE REVIEW

**Comment by juliohm** [comment]
Hi @yurivish, did you have a chance to take a look into this?

**Comment by yurivish** [comment]
Hey! Sorry for the delay — this looked so comprehensive I wanted to set time aside to actually have a look. My first instinct is to suggest that this be kept separate, since it doesn't make sense to me that `GeoStats` packages are required to generate Turing patterns, and the approaches to optional dependencies in Julia don't seem to be very good at the moment.

Also, could you explain a bit more about what exactly this is doing? 😄I came to Turing patterns from the artistic side and am not sure I understand what they have to do with geological stuff.

**Comment by yurivish** [comment]
And in terms of tagging a release, sure, I can do that this weekend. Will make a note!

**Comment by juliohm** [comment]
Yeah! I think that we could use `Requires.jl` and optionally load the piece of code that depends on `GeoStatsBase.jl` that would solve all our issues I believe! I will try update the PR, it should be very easy to do. Basically TuringPatterns.jl will remain as is, and will only have this connection with GeoStats.jl when both packages are loaded in a session. That would be perfect.

The patterns per see don't have much relation with geology, but they are spatial patterns anyways coming from a distribution that Turing suggested. I think of GeoStats.jl as a collection of algorithms for sampling spatial data (the `SimulationProblem` type). There are many algorithms that I am planning to add in the future, and TuringPatterns.jl is very useful for illustration purposes. It is all about assumptions you make about the subsurface when you construct these models. In the workshop I want to show participants the variety of patterns you can construct once you pick a set of assumptions.

**Comment by juliohm** [comment]
Hi @yurivish , I've updated the PR as we discussed :+1: Could you please take a look when you have time?

Thank you,
-Julio

**Comment by yurivish** [comment]
Hey, this looks great – I'll update the package and merge this weekend! Thank you for the contribution!

**Comment by yurivish** [comment]
I can't test this branch on my laptop due to build issues for the test dependencies, even after reinstalling and rebuilding a number of packages... Hm.

```
v1.1) pkg> test TuringPatterns
   Testing TuringPatterns
 Resolving package versions...
 Installed GeoStatsBase ────────── v0.3.5
 Installed Tables ──────────────── v0.1.17
 Installed Plots ───────────────── v0.23.1
 Installed NearestNeighbors ────── v0.4.3
 Installed VisualRegressionTests ─ v0.3.0
 Installed GeoStatsDevTools ────── v0.3.9
 Installed GR ──────────────────── v0.38.1
  Building GR ───→ `~/.julia/packages/GR/IVBgs/deps/build.log`
  Building Plots → `~/.julia/packages/Plots/gylTh/deps/build.log`
    Status `/var/folders/qh/rzmdwff11pq_swsskpcxy0h00000gn/T/tmp6EwnPi/Manifest.toml`
  [621f4979] AbstractFFTs v0.3.2
  [7d9fca2a] Arpack v0.3.0
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.3
  [336ed68f] CSV v0.4.3
  [aafaddc9] CatIndices v0.2.0
  [324d7699] CategoricalArrays v0.5.2
  [944b1d66] CodecZlib v0.5.2
  [3da002f7] ColorTypes v0.7.5
  [c3611d14] ColorVectorSpace v0.6.2
  [5ae59095] Colors v0.9.5
  [34da2185] Compat v1.5.1
  [ed09eef8] ComputationalResources v0.3.0
  [8f4d0f93] Conda v1.2.0
  [d38c429a] Contour v0.5.1
  [dc8bdbbb] CustomUnitRanges v0.2.0
  [a93c6f00] DataFrames v0.17.1
  [9a8bc11e] DataStreams v0.4.1
  [864edb3b] DataStructures v0.15.0
  [b4f34e82] Distances v0.8.0
  [31c24e10] Distributions v0.16.4
  [4f61f5a4] FFTViews v0.2.0
  [7a1cc6ca] FFTW v0.2.4
  [5789e2e9] FileIO v1.0.5
  [53c48c17] FixedPointNumbers v0.5.3
  [28b8d3ca] GR v0.38.1
  [323cb8eb] GeoStatsBase v0.3.5
  [19e549d1] GeoStatsDevTools v0.3.9
  [a2bd30eb] Graphics v0.4.0
  [a09fc81d] ImageCore v0.7.4
  [6a3955dd] ImageFiltering v0.5.3
  [6218d12a] ImageMagick v0.7.1
  [82899510] IteratorInterfaceExtensions v0.1.1
  [682c06a0] JSON v0.20.0
  [dbb5928d] MappedArrays v0.2.1
  [442fdcdd] Measures v0.3.0
  [e1d29d7a] Missings v0.4.0
  [77ba4419] NaNMath v0.3.2
  [b8a86587] NearestNeighbors v0.4.3
  [6fe1bfb0] OffsetArrays v0.10.0
  [bac558e1] OrderedCollections v1.0.2
  [90014a1f] PDMats v0.9.6
  [5432bcbf] PaddedViews v0.4.2
  [d96e819e] Parameters v0.10.3
  [69de0a69] Parsers v0.2.18
  [ccf2f8ad] PlotThemes v0.3.0
  [995b91a9] PlotUtils v0.5.5
  [91a5bcdd] Plots v0.23.1
  [1fd47b50] QuadGK v2.0.3
  [dca85d43] QuartzImageIO v0.5.2
  [3cdcf5f2] RecipesBase v0.6.0
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [79098fc4] Rmath v0.5.0
  [992d4aef] Showoff v0.2.1
  [a2af1166] SortingAlgorithms v0.3.1
  [276daf66] SpecialFunctions v0.7.2
  [90137ffa] StaticArrays v0.10.3
  [2913bbd2] StatsBase v0.27.0
  [4c63d2b9] StatsFuns v0.8.0
  [3783bdb8] TableTraits v0.4.1
  [bd369af6] Tables v0.1.17
  [06e1c1a7] TiledIteration v0.2.3
  [3bb67fe8] TranscodingStreams v0.8.1
  [f3441f9e] TuringPatterns v0.0.0 [`~/.julia/dev/TuringPatterns`]
  [30578b45] URIParser v0.4.0
  [81def892] VersionParsing v1.1.3
  [34922c18] VisualRegressionTests v0.3.0
  [ea10d353] WeakRefStrings v0.5.7
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [9fa8497b] Future  [`@stdlib/Future`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [9abbd945] Profile  [`@stdlib/Profile`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [4607b0f0] SuiteSparse  [`@stdlib/SuiteSparse`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `/private/var/folders/qh/rzmdwff11pq_swsskpcxy0h00000gn/T/tmp6EwnPi/Project.toml`
  [4c0ca9eb] + Gtk v0.16.5
  Updating `/private/var/folders/qh/rzmdwff11pq_swsskpcxy0h00000gn/T/tmp6EwnPi/Manifest.toml`
  [e1450e63] + BufferedStreams v1.0.0
  [159f3aea] + Cairo v0.5.6
  [4c0ca9eb] + Gtk v0.16.5
  [0862f596] + HTTPClient v0.2.1
  [d9be37ee] + Homebrew v0.7.1
  [b27032c2] + LibCURL v0.4.1
  [522f3ed2] + LibExpat v0.5.0
  [2ec943e9] + Libz v1.0.0
  [c17dfb99] + WinRPM v0.4.2
ERROR: LoadError: LoadError: LoadError: Unable to load

_jl_libgobject (/Users/yurivish/.julia/packages/Homebrew/l8kUw/deps/usr/lib/libgobject-2.0.dylib)

Please re-run Pkg.build(package), and restart Julia.
Stacktrace:
 [1] error(::String, ::String) at ./error.jl:42
 [2] @checked_lib(::LineNumberNode, ::Module, ::Any, ::Any) at /Users/yurivish/.julia/packages/Cairo/CXPG1/deps/deps.jl:11
 [3] include at ./boot.jl:326 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include at ./sysimg.jl:29 [inlined]
 [6] include(::String) at /Users/yurivish/.julia/packages/Cairo/CXPG1/src/Cairo.jl:3
 [7] top-level scope at none:0
 [8] include at ./boot.jl:326 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:328 [inlined]
 [13] eval(::Expr) at ./client.jl:404
 [14] top-level scope at ./none:3
in expression starting at /Users/yurivish/.julia/packages/Cairo/CXPG1/deps/deps.jl:20
in expression starting at /Users/yurivish/.julia/packages/Cairo/CXPG1/deps/deps.jl:20
in expression starting at /Users/yurivish/.julia/packages/Cairo/CXPG1/src/Cairo.jl:9
ERROR: LoadError: Failed to precompile Cairo [159f3aea-2a34-519c-b102-8c37f9878175] to /Users/yurivish/.julia/compiled/v1.1/Cairo/l6vnT.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:328 [inlined]
 [11] eval(::Expr) at ./client.jl:404
 [12] top-level scope at ./none:3
in expression starting at /Users/yurivish/.julia/packages/Gtk/RwVPb/src/Gtk.jl:32
ERROR: LoadError: Failed to precompile Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44] to /Users/yurivish/.julia/compiled/v1.1/Gtk/Vjnq0.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [3] _require(::Base.PkgId) at ./loading.jl:960
 [4] require(::Base.PkgId) at ./loading.jl:858
 [5] require(::Module, ::Symbol) at ./loading.jl:853
 [6] top-level scope at /Users/yurivish/.julia/dev/TuringPatterns/test/runtests.jl:15
 [7] include at ./boot.jl:326 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] include(::String) at ./client.jl:403
 [11] top-level scope at none:0
in expression starting at /Users/yurivish/.julia/dev/TuringPatterns/test/runtests.jl:13
ERROR: Package TuringPatterns errored during testing
```

**Comment by yurivish** [comment]
@juliohm I figured I'd merge this since it all looks good, and I trust that you tested it on your end. The installation issues don't seem related at all to your work, but to large packages that it depends on.

Thanks again for the contribution and changes to minimize the dependencies! :)

**Comment by juliohm** [comment]
Thank you @yurivish! :) I'll update the GeoStats.jl README to point to your
solver when I'm back to work this Thursday. That is great news :)

**Comment by juliohm** [comment]
Hi @yurivish , did you have a chance to tag a version with attobot?

**Comment by yurivish** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/22075

**Comment by juliohm** [comment]
Thanks! :)

**Pull request merged**
